{
 "title": "Zabbix ML — Прогнозирование дискового пространства",
 "tags": [
  "zabbix",
  "ml",
  "capacity"
 ],
 "time": { "from": "now-1y", "to": "now+3M" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Хост",
    "query": "SELECT DISTINCT host\nFROM prediction_targets\nWHERE enabled = true\nORDER BY host"
   },
   {
    "name": "disk",
    "label": "Маунтпоинт",
    "query": "SELECT name AS __text, name AS __value\nFROM prediction_targets\nWHERE host = '$host' AND enabled = true"
   }
  ]
 },
 "panels": [
  {
   "title": "$disk заполнение %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$disk. Space utilization$/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$disk заполнение ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*:(.*)/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$disk. Used space/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*:(.*)/",
        "$1"
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$disk. Total space/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Прогноз использования",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH targets AS (\r\n  SELECT itemid, name\r\n  FROM prediction_targets\r\n  WHERE host = '$host'\r\n    AND name = '$disk'\r\n    AND enabled = true\r\n),\r\nlatest_runs AS (\r\n  SELECT \r\n    f.itemid,\r\n    MAX(f.forecast_run_at) AS run_at\r\n  FROM forecasts f\r\n  JOIN targets t ON f.itemid = t.itemid\r\n  GROUP BY f.itemid\r\n)\r\nSELECT\r\n  t.name AS \"Маунтпоинт\",\r\n  ROUND(AVG(CASE WHEN f.ds >= NOW() + INTERVAL '30 days' THEN f.yhat END)::NUMERIC, 2) AS \"30d (TB)\",\r\n  ROUND(AVG(CASE WHEN f.ds >= NOW() + INTERVAL '60 days' THEN f.yhat END)::NUMERIC, 2) AS \"60d (TB)\",\r\n  ROUND(AVG(CASE WHEN f.ds >= NOW() + INTERVAL '88 days' THEN f.yhat END)::NUMERIC, 2) AS \"90d (TB)\"\r\nFROM forecasts f\r\nJOIN targets t ON f.itemid = t.itemid\r\nJOIN latest_runs l ON f.itemid = l.itemid AND f.forecast_run_at = l.run_at\r\nGROUP BY t.name\r\nORDER BY t.name;"
    }
   ]
  },
  {
   "title": "История и прогноз использования диска $disk на $host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH target AS (\r\n  SELECT itemid\r\n  FROM prediction_targets\r\n  WHERE host = '$host'\r\n    AND name = '$disk'\r\n    AND enabled = true\r\n),\r\nlatest_run AS (\r\n  SELECT MAX(run_id) AS run_id  -- ← используем run_id!\r\n  FROM forecasts f\r\n  JOIN target t ON f.itemid = t.itemid\r\n)\r\nSELECT\r\n  f.ds AS \"time\",\r\n  f.yhat AS \"forecast\",\r\n  f.yhat_lower AS \"lower\",\r\n  f.yhat_upper AS \"upper\"\r\nFROM forecasts f\r\nJOIN target t ON f.itemid = t.itemid\r\nJOIN latest_run l ON f.run_id = l.run_id  -- ← join по run_id\r\nORDER BY f.ds;"
    },
    {
     "rawSql": "SELECT\r\n  TO_TIMESTAMP(z.clock) AS \"time\",\r\n  z.value_avg AS \"actual\"\r\nFROM zabbix_trends z\r\nJOIN prediction_targets p \r\n  ON z.itemid = p.itemid\r\nWHERE\r\n  p.host = '$host'\r\n  AND p.name = '$disk'\r\n  AND p.enabled = true\r\n  AND z.clock >= EXTRACT(EPOCH FROM NOW() - INTERVAL '360 days')\r\nORDER BY z.clock;"
    },
    {
     "rawSql": "SELECT\r\n  ds AS \"time\",\r\n  yhat AS \"demo_forecast\"\r\nFROM demo_forecasts\r\nWHERE itemid IN (\r\n  SELECT itemid \r\n  FROM prediction_targets \r\n  WHERE host = '$host' \r\n    AND name = '$disk' \r\n    AND enabled = true\r\n)\r\n  AND yhat IS NOT NULL\r\nORDER BY ds;"
    }
   ]
  },
  {
   "title": "История и прогноз использования диска $disk на $host",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  TO_TIMESTAMP(z.clock) AS \"time\",\r\n  z.value_avg AS \"actual\"\r\nFROM zabbix_trends z\r\nJOIN prediction_targets p \r\n  ON z.itemid = p.itemid\r\nWHERE\r\n  p.host = '$host'\r\n  AND p.name = '$disk'\r\n  AND p.enabled = true\r\n  AND z.clock >= EXTRACT(EPOCH FROM NOW() - INTERVAL '360 days')\r\nORDER BY z.clock;"
    }
   ]
  }
 ]
}